---
name: Deploy to Hugging Face
on:
  push:
    branches: [ main ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install LFS
        run: git lfs install

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # 1. Registra TUDO que é binário no LFS para o Hugging Face não reclamar
          git lfs track "*.png"
          git lfs track "*.jpg"
          git lfs track "*.webp"
          git lfs track "*.mp3"
          git lfs track "*.pdf"
          git lfs track "*.mp4"
          git add .gitattributes
          
          # 2. Faz o commit dessas marcações
          git add -A
          git commit -m "Preparando arquivos necessários via LFS" || echo "Sem mudanças"
          
          # 3. Limpa o histórico para o push ser leve
          git checkout --orphan latest_branch
          git add -A
          git commit -m "Deploy final com todos os assets"
          git branch -D main
          git branch -m main
          
          # 4. Push forçado
          git push -f https://Umpemaus:$HF_TOKEN@huggingface.co/spaces/Umpemaus/umpemaus main
